# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: swift
xcode_workspace: PlanOutSwift.xcworkspace
script:
- pod lib lint --allow-warnings
